
.TH rpmgr "8" "Feb. 2025" "System Files"
.SH NAME
.B rpmgr
\- graphical management of RPM software packages
.SH SYNOPSIS
.SH DESCRIPTION
.B RPMgr
is a frontend for the
.B dnf5
and
.B rpm
package managent system. It allows you to perform most actions of the command line tool
.B dnf5
in a graphical environment. This includes installing, upgrading, downgrading  and removing of single packages or even upgrading your whole system.
.PP
A manual with detailed instructions can be found in the help menu of
.B RPMgr.
.SH OPTIONS
.B RPMgr
accepts only an optional filname to install from the command line.  All other functions are handled internally.
.SH AUTHORS
.B RPMgr
is written by Jem Miller <jem@mlsoft.org>.
.PP
This manual page was  written by Jem Miller
.SH COPYRIGHT
Copyright (C) 2025 by Jim Miller and Missing Link Software
.PP
There is NO warranty.
.br
You may redistribute this software under the terms of  the  License. For more information about these matters, see the file named
.B license.txt.
Or see the License in the help menu item.
