#!/bin/bash

# Run this script with sudo or as root, from the directory that you unpack the beta .zip package into.
# This script only needs to be run when you first start beta testing to set up the environment and get files copied.
# Once packaged, the RPM will do all of this for us. 

dbdir="/usr/share/rpmgr"
_datadir="/usr/share"
_bindir="/usr/bin"
dbfile="/usr/share/rpmgr/rpmgr.db"

/bin/rm -rf /usr/share/rpmgr

install -D -m755    rpmgr              "{$_datadir}/rpmgr"
install -D -m755    lhelp              "{$_bindir}/lhelp"
install -D -m644    rpmgr.desktop      "{$_datadir}/applications/rpmgr.desktop"
install -D -m644    rpmgr.png          "{$_datadir}/pixmaps/rpmgr.png"
install -D -m644    rpmgr.8.gz         "{$_datadir}/man/man8/rpmgr.8.gz"

if [ ! -f "{$dbfile}" ]; then
install -D -m774    rpmgr.db           "{$dbfile}"
fi;

install -D -m644    rpmgr.chm          "{$_dbdir}/rpmgr.chm"

/bin/mkdir -m=775 -p /usr/share/doc/rpmgr
/bin/mkdir -m=775 -p /usr/share/licenses/rpmgr

install -D -m644 LICENSE /usr/share/licenses/rpmgr
install -D -m644 mlsoft2.1.txt /usr/share/licenses/rpmgr

/usr/bin/chown root:wheel "$dbdir"
/usr/bin/chmod 775 "$dbdir"
/usr/bin/ln -s /usr/bin/rpmgr /usr/share/rpmgr/rpmgr
/usr/bin/chown root:wheel /usr/bin/rpmgr
/usr/bin/chmod 754 /usr/bin/rpmgr
/usr/bin/chmod 755 /usr/bin/lhelp
/usr/bin/chmod 644 /usr/share/doc/rpmgr/*
/usr/bin/chmod 644 /usr/share/rpmgr/rpmgr.chm
